version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: fintech_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fintech_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: fintech_app
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: fintech_db
      DB_USER: root
      DB_PASSWORD: root
    ports:
      - "8094:8094"

volumes:
  db_data:
